Take 2: Still getting the weird compiler error.
No idea what to make of it. Maybe it's a compiler bug?

I tried type casting all of the results of the add to Words, but that didn't change anything. It says its an issue of getting objects and assigning them to words, but there are no uncasted objects in the specified method. I'll keep poking at it, but later because it works when I'm not storing it as a package, and the rest is all about the compiler.

Error Message:
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Processor/ALU.multiply()V @136: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[7]) is not assignable to 'Processor/Word'
  Current Frame:
    bci: @136
    flags: { }
    locals: { 'Processor/ALU' }
    stack: { 'Processor/ALU', 'Processor/ALU', 'Processor/ALU', 'Processor/ALU', 'java/lang/Object', 'java/lang/Object', 'java/lang/Object', 'java/lang/Object' }
  Bytecode:
    0000000: 2a2a 2a2a 2ab4 0018 03b6 0098 b600 2c99
    0000010: 000e 2ab4 0016 03b6 0081 a700 0bbb 0013
    0000020: 5903 b700 b52a b400 1804 b600 98b6 002c
    0000030: 9900 0e2a b400 1604 b600 81a7 000b bb00
    0000040: 1359 03b7 00b5 2ab4 0018 05b6 0098 b600
    0000050: 2c99 000e 2ab4 0016 05b6 0081 a700 0bbb
    0000060: 0013 5903 b700 b52a b400 1806 b600 98b6
    0000070: 002c 9900 0e2a b400 1606 b600 81a7 000b
    0000080: bb00 1359 03b7 00b5 b600 b72a 2ab4 0018
    0000090: 07b6 0098 b600 2c99 000e 2ab4 0016 07b6
    00000a0: 0081 a700 0bbb 0013 5903 b700 b52a b400
    00000b0: 1808 b600 98b6 002c 9900 0e2a b400 1608
    00000c0: b600 81a7 000b bb00 1359 03b7 00b5 2ab4
    00000d0: 0018 1006 b600 98b6 002c 9900 0f2a b400
    00000e0: 1610 06b6 0081 a700 0bbb 0013 5903 b700
    00000f0: b52a b400 1810 07b6 0098 b600 2c99 000f
    0000100: 2ab4 0016 1007 b600 81a7 000b bb00 1359
    0000110: 03b7 00b5 b600 b72a 2ab4 0018 1008 b600
    0000120: 98b6 002c 9900 0f2a b400 1610 08b6 0081
    0000130: a700 0bbb 0013 5903 b700 b52a b400 1810
    0000140: 09b6 0098 b600 2c99 000f 2ab4 0016 1009
    0000150: b600 81a7 000b bb00 1359 03b7 00b5 2ab4
    0000160: 0018 100a b600 98b6 002c 9900 0f2a b400
    0000170: 1610 0ab6 0081 a700 0bbb 0013 5903 b700
    0000180: b52a b400 1810 0bb6 0098 b600 2c99 000f
    0000190: 2ab4 0016 100b b600 81a7 000b bb00 1359
    00001a0: 03b7 00b5 b600 b72a 2ab4 0018 100c b600
    00001b0: 98b6 002c 9900 0f2a b400 1610 0cb6 0081
    00001c0: a700 0bbb 0013 5903 b700 b52a b400 1810
    00001d0: 0db6 0098 b600 2c99 000f 2ab4 0016 100d
    00001e0: b600 81a7 000b bb00 1359 03b7 00b5 2ab4
    00001f0: 0018 100e b600 98b6 002c 9900 0f2a b400
    0000200: 1610 0eb6 0081 a700 0bbb 0013 5903 b700
    0000210: b52a b400 1810 0fb6 0098 b600 2c99 000f
    0000220: 2ab4 0016 100f b600 81a7 000b bb00 1359
    0000230: 03b7 00b5 b600 b7b6 00b7 2a2a 2ab4 0018
    0000240: 1010 b600 98b6 002c 9900 0f2a b400 1610
    0000250: 10b6 0081 a700 0bbb 0013 5903 b700 b52a
    0000260: b400 1810 11b6 0098 b600 2c99 000f 2ab4
    0000270: 0016 1011 b600 81a7 000b bb00 1359 03b7
    0000280: 00b5 2ab4 0018 1012 b600 98b6 002c 9900
    0000290: 0f2a b400 1610 12b6 0081 a700 0bbb 0013
    00002a0: 5903 b700 b52a b400 1810 13b6 0098 b600
    00002b0: 2c99 000f 2ab4 0016 1013 b600 81a7 000b
    00002c0: bb00 1359 03b7 00b5 b600 b72a 2ab4 0018
    00002d0: 1014 b600 98b6 002c 9900 0f2a b400 1610
    00002e0: 14b6 0081 a700 0bbb 0013 5903 b700 b52a
    00002f0: b400 1810 15b6 0098 b600 2c99 000f 2ab4
    0000300: 0016 1015 b600 81a7 000b bb00 1359 03b7
    0000310: 00b5 2ab4 0018 1016 b600 98b6 002c 9900
    0000320: 0f2a b400 1610 16b6 0081 a700 0bbb 0013
    0000330: 5903 b700 b52a b400 1810 17b6 0098 b600
    0000340: 2c99 000f 2ab4 0016 1017 b600 81a7 000b
    0000350: bb00 1359 03b7 00b5 b600 b72a 2ab4 0018
    0000360: 1018 b600 98b6 002c 9900 0f2a b400 1610
    0000370: 18b6 0081 a700 0abb 0013 59b7 0015 2ab4
    0000380: 0018 1019 b600 98b6 002c 9900 0f2a b400
    0000390: 1610 19b6 0081 a700 0abb 0013 59b7 0015
    00003a0: 2ab4 0018 101a b600 98b6 002c 9900 0f2a
    00003b0: b400 1610 1ab6 0081 a700 0abb 0013 59b7
    00003c0: 0015 2ab4 0018 101b b600 98b6 002c 9900
    00003d0: 0f2a b400 1610 1bb6 0081 a700 0abb 0013
    00003e0: 59b7 0015 b600 b72a 2ab4 0018 101c b600
    00003f0: 98b6 002c 9900 0f2a b400 1610 1cb6 0081
    0000400: a700 0abb 0013 59b7 0015 2ab4 0018 101d
    0000410: b600 98b6 002c 9900 0f2a b400 1610 1db6
    0000420: 0081 a700 0abb 0013 59b7 0015 2ab4 0018
    0000430: 101e b600 98b6 002c 9900 0f2a b400 1610
    0000440: 1eb6 0081 a700 0abb 0013 59b7 0015 2ab4
    0000450: 0018 101f b600 98b6 002c 9900 0f2a b400
    0000460: 1610 1fb6 0081 a700 0abb 0013 59b7 0015
    0000470: b600 b7b6 00b7 b600 91b5 001a b1
  Stackmap Table:
    full_frame(@29,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#1]})
    full_frame(@37,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#1],Object[#3]})
    full_frame(@62,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#1],Object[#3]})
    full_frame(@70,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#1],Object[#3],Object[#3]})
    full_frame(@95,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#1],Object[#3],Object[#3]})
    full_frame(@103,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@128,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@136,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#1],Object[#3],Object[#3],Object[#3],Object[#3]})
    full_frame(@165,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#1]})
    full_frame(@173,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#1],Object[#3]})
    full_frame(@198,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#1],Object[#3]})
    full_frame(@206,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@233,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@241,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@268,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@276,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3],Object[#3]})
    full_frame(@307,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#1]})
    full_frame(@315,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3]})
    full_frame(@342,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3]})
    full_frame(@350,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@377,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@385,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@412,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@420,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3],Object[#3]})
    full_frame(@451,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1]})
    full_frame(@459,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3]})
    full_frame(@486,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3]})
    full_frame(@494,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@521,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@529,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@556,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@564,{Object[#1]},{Object[#1],Object[#1],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3],Object[#3]})

    full_frame(@599,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#1]})
    full_frame(@607,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#1],Object[#3]})
    full_frame(@634,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#1],Object[#3]})
    full_frame(@642,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#1],Object[#3],Object[#3]})
    full_frame(@669,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#1],Object[#3],Object[#3]})
    full_frame(@677,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@704,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@712,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#1],Object[#3],Object[#3],Object[#3],Object[#3]})
    full_frame(@743,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#1]})
    full_frame(@751,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#1],Object[#3]})
    full_frame(@778,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#1],Object[#3]})
    full_frame(@786,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@813,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@821,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@848,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@856,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3],Object[#3]})
    full_frame(@887,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#1]})
    full_frame(@894,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3]})
    full_frame(@921,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3]})
    full_frame(@928,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@955,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@962,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@989,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@996,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3],Object[#3]})
    full_frame(@1027,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1]})
    full_frame(@1034,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3]})
    full_frame(@1061,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3]})
    full_frame(@1068,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@1095,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3]})
    full_frame(@1102,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@1129,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3]})
    full_frame(@1136,{Object[#1]},{Object[#1],Object[#1],Object[#19],Object[#1],Object[#19],Object[#19],Object[#19],Object[#1],Object[#3],Object[#3],Object[#3],Object[#3]})

 at UnitTest.ALU_logic(UnitTest.java:557)
```